services:
  mongo:
    image: mongo:6-jammy
    container_name: analytics-mongo
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    networks:
      - analytics-network

  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    container_name: analytics-server
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/analytics-bi
      - NODE_ENV=production
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - analytics-network

  client:
    build:
      context: .
      dockerfile: apps/client/Dockerfile
    container_name: analytics-client
    ports:
      - "3000:80"
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - analytics-network

networks:
  analytics-network:
    driver: bridge

volumes:
  mongo_data:
