import { Transform } from 'node:stream';
import { TYPE_CLEANER_MAP } from './cleaner.js';
import { parseDate } from './normalizer.js';
import DLQRecord from '../../models/DLQRecord.js';

// ─── What this file receives from other roles ─────────────────────────────────
//
//  FROM ROLE 4 (The Parser):
//    • Each `chunk` is a plain JS object representing one parsed row.
//      e.g. { productName: "laptop pro", price: "1,299.99", date: "44562" }
//    • The `datasetId` string is passed in when the stream is constructed.
//      Role 4 generates this ID when it creates the raw dataset in MongoDB.
//
//  FROM ROLE 6 (Schema Inference):
//    • An array called `inferredSchema` passed into the constructor.
//      This comes from the Metadata collection that Role 6 writes to after
//      classifying columns. Each entry looks like:
//        {
//          name:     "price",       // column key, must match the chunk's keys
//          type:     "decimal",     // drives which cleaner we pick
//          role:     "measure",     // "dimension" | "measure" | "attribute"
//          nullable: false          // if false + value is null → DLQ
//        }
//
// ─────────────────────────────────────────────────────────────────────────────

// Maps date/timestamp types to the normalizer.
const DATE_TYPES = new Set(['date', 'datetime', 'timestamp']);

// Decide which cleaning function to use for a given schema column.
const resolveCleanerForColumn = (schemaColumn) => {
    const type = schemaColumn.type?.toLowerCase();
    if (DATE_TYPES.has(type)) return parseDate;
    return TYPE_CLEANER_MAP[type] || null; // null = unknown type, pass through raw
};

// ─── DTS Engine Stream ────────────────────────────────────────────────────────
class DTSEngineStream extends Transform {
    /**
     * @param {string}   datasetId      - ID generated by Role 4 / Role 3 for this upload
     * @param {Array}    inferredSchema - Schema array written by Role 6 to the Metadata collection
     */
    constructor(datasetId, inferredSchema = []) {
        super({ objectMode: true });
        this.datasetId = datasetId;
        this.dlqBuffer = [];

        // Build a fast lookup: columnName → { cleanerFn, nullable, type, role }
        this.schemaMap = {};
        for (const col of inferredSchema) {
            this.schemaMap[col.name] = {
                cleanerFn: resolveCleanerForColumn(col),
                nullable:  col.nullable !== false, // default: nullable unless explicitly false
                type:      col.type,
                role:      col.role,
            };
        }
    }

    async _transform(chunk, encoding, callback) {
        const cleanedRow = {};
        const validationErrors = [];

        for (const [key, rawValue] of Object.entries(chunk)) {
            const colMeta = this.schemaMap[key];

            // ── Column not in schema (Role 6 hasn't seen it) ─────────────────
            // Pass through untouched. Role 6 may have missed it or schema is partial.
            if (!colMeta) {
                cleanedRow[key] = rawValue;
                continue;
            }

            const { cleanerFn, nullable, type } = colMeta;

            // ── Apply the cleaner ─────────────────────────────────────────────
            let cleanedValue;
            if (cleanerFn) {
                cleanedValue = cleanerFn(rawValue);
            } else {
                // Unknown type — no cleaner registered, pass through
                cleanedValue = rawValue;
            }

            // ── DLQ Rule: null on a non-nullable column ───────────────────────
            // We never invent values. If a required field is null/empty after
            // cleaning, the record is unfixable → goes to DLQ.
            if (cleanedValue === null && !nullable) {
                validationErrors.push({
                    column:  key,
                    type:    'missing_required_value',
                    message: `Column "${key}" (type: ${type}) is required but value is null or unparseable after cleaning.`,
                    raw:     rawValue,
                });
            }

            // ── DLQ Rule: type coercion completely failed ─────────────────────
            // e.g. the cleaner returned null for a number field because the raw
            // value was "banana". We flag it but still write it as null so the
            // record flows through for further checks.
            if (cleanedValue === null && rawValue !== null && rawValue !== '' && nullable) {
                validationErrors.push({
                    column:  key,
                    type:    'unparseable_value',
                    severity: 'warning',
                    message: `Column "${key}" (type: ${type}) could not be parsed. Raw value: "${rawValue}". Stored as null.`,
                    raw:     rawValue,
                });
            }

            cleanedRow[key] = cleanedValue;
        }

        // ── Route to DLQ if any hard errors exist ─────────────────────────────
        const hardErrors = validationErrors.filter(e => e.type === 'missing_required_value');
        if (hardErrors.length > 0) {
            this.dlqBuffer.push({
                datasetId: this.datasetId,
                rawData:   chunk,
                error:     hardErrors.map(e => e.message).join(' | '),
                status:    'UNFIXABLE',
            });
            console.log(`[DTS] Row buffered for DLQ (${hardErrors.length} hard error(s))`);
            return callback();
        }

        // ── Emit cleaned row (warnings are non-blocking) ──────────────────────
        if (validationErrors.length > 0) {
            console.warn(`[DTS] Row has warnings (continuing):`, validationErrors);
        }
        callback(null, cleanedRow);

    }

    async _flush(callback) {
        if (this.dlqBuffer.length > 0) {
            await DLQRecord.insertMany(this.dlqBuffer);
            console.log(`[DTS] Flushed ${this.dlqBuffer.length} records to DLQ`);
        }
        callback();
    }
}

export default DTSEngineStream;